name: Run Unit Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - '**/*.md'
      - '**/*.jpg'
      - '**/README.txt'
      - '**/LICENSE.txt'
      - 'docs/**'

env:
  BUILD_TYPE: Release

jobs:
  build-windows:
    name: Windows
    runs-on: windows-latest
    env:
      CMAKE_GENERATOR: Visual Studio 17 2022
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Cache AWS SDK libraries
        id: cache-static-aws-sdk
        uses: actions/cache@v4
        if: always() && steps.cache-static-aws-sdk.outputs.cache-hit != 'true'
        with:
          path: |
            aws_sdk
          key: ${{ runner.os }}-aws-sdk-static-lib

      - name: Build and install AWS SDK C++
        working-directory: ./scripts
        if: steps.cache-static-aws-sdk.outputs.cache-hit != 'true'
        run: |
          .\build_aws_sdk_win.ps1 x64 ${{env.BUILD_TYPE}} OFF "${{env.CMAKE_GENERATOR}}"

      - name: Create build environment
        shell: bash
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        shell: bash
        run: cmake -S . -B build
          -G "$CMAKE_GENERATOR"
          -DENABLE_UNIT_TESTS=TRUE

      - name: Build Project
        shell: bash
        run: cmake --build build
          --config ${{env.BUILD_TYPE}}

      - name: Run unit tests
        if: success()
        working-directory: ./build/test/unit_test
        shell: bash
        run: |
          ctest -C ${{env.BUILD_TYPE}} --output-on-failure
  build-mac:
    name: macOS
    runs-on: macos-14
    env:
      CMAKE_GENERATOR: Unix Makefiles
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Cache AWS SDK libraries
        id: cache-static-aws-sdk
        uses: actions/cache@v4
        if: always() && steps.cache-static-aws-sdk.outputs.cache-hit != 'true'
        with:
          path: |
            aws_sdk
          key: ${{ runner.os }}-aws-sdk-cache-lib

      - name: Build and install AWS SDK C++
        working-directory: ./scripts
        if: steps.cache-static-aws-sdk.outputs.cache-hit != 'true'
        run: |
          ./build_aws_sdk_unix.sh $BUILD_TYPE

      - name: Create build environment
        run: cmake -E make_directory ${{ github.workspace }}/build

      - name: Configure CMake
        run: cmake -S . -B build
          -G "$CMAKE_GENERATOR"
          -DENABLE_UNIT_TESTS=TRUE

      - name: Build Project
        run: cmake --build build --config $BUILD_TYPE

      - name: Run unit tests
        if: success()
        working-directory: ./build/test/unit_test
        run: |
          ctest -C $BUILD_TYPE --output-on-failure
